### ISSUE TITLE
天天算法 LeetCode-674-最长连续递增序列

### ISSUE THREAD

**Issue by guanpengchn** [guanpengchn/blog#12]

**Comment by guanpengchn** [comment]
打卡第7天

**Comment by intbjw** [comment]
【打卡】LeetCode-674-最长连续递增序列

`
#列表为[]有坑
class Solution:
    def findLengthOfLCIS(self, nums: List[int]) -> int:
        if len(nums) < 2:
            return len(nums)
        Max = 0
        temp = 1
        for i in range(1,len(nums)):
            if nums[i] > nums[i-1]:
                temp = temp + 1
            else: 
                temp = 1
            Max = max(Max,temp)
        return Max`

**Comment by Adnios** [comment]
【打卡】`class Solution {
public:
    int findLengthOfLCIS(vector<int>& nums) {
        if(nums.empty()){
            return 0;
        }
        int ans=1;
        int tempans=1;
        for(int i=1;i<nums.size();i++){
            if(nums[i-1]>=nums[i]){
                ans=max(ans,tempans);
                tempans=1;
            }
            else{
                tempans++;
            }

        }
        ans=max(ans,tempans);
        return ans;
    }
};`
