### ISSUE TITLE
画解算法 92-反转链表 II

### ISSUE THREAD

**Issue by guanpengchn** [guanpengchn/blog#13]

**Comment by dljgs1** [comment]
JS:
Runtime: 52 ms, faster than 96.39% of JavaScript online submissions for Reverse Linked List II.
Memory Usage: 33.7 MB, less than 81.27% of JavaScript online submissions for Reverse Linked List II.

--------------
var reverseBetween = function(head, m, n) {
    var i = 1;
    var vhead = {next:head};
    var last = vhead;
    var ptr = head;
    while(i<m){
        last = last.next;
        ptr=ptr.next;
        i++;
    }
    var st1 = last;
    var st2 = ptr;
    while(i<=n){
        i++;
        var temp=ptr.next;
        ptr.next = last;
        last = ptr;
        ptr = temp;
    }
    st1.next = last;
    st2.next = ptr;
    return vhead.next;
};

**Comment by intbjw** [comment]
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def reverseBetween(self, head: ListNode, m: int, n: int) -> ListNode:
        newList = ListNode(0)
        newList.next = head
        pre = newList
        for _ in range(1,m):
            pre = pre.next
        head = pre.next
        for _ in range(m,n):
            nex = head.next
            head.next = nex.next
            nex.next = pre.next
            pre.next = nex
        return newList.next

**Comment by intbjw** [comment]
class Solution:
    def reverseBetween(self, head: ListNode, m: int, n: int) -> ListNode:
        newList = ListNode(0)
        newList.next = head
        pre = newList
        for _ in range(1,m):
            pre = pre.next
        head = pre.next
        for _ in range(m,n):
            nex = head.next
            head.next = nex.next
            nex.next = pre.next
            pre.next = nex
        return newList.next

**Comment by intbjw** [comment]
```
class Solution:
    def reverseBetween(self, head: ListNode, m: int, n: int) -> ListNode:
        newList = ListNode(0)
        newList.next = head
        pre = newList
        for _ in range(1,m):
            pre = pre.next
        head = pre.next
        for _ in range(m,n):
            nex = head.next
            head.next = nex.next
            nex.next = pre.next
            pre.next = nex
        return newList.next
```

**Comment by Adnios** [comment]
打卡，暴力求解
`/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
class Solution {
public:
    ListNode* reverseBetween(ListNode* head, int m, int n) {
        ListNode* p=head;
        ListNode* q=head;
        int i=0;
        vector<int> nums;
        while(p){
            i++;
            if(m<=i&&i<=n){
                nums.push_back(p->val);
            }
            p=p->next;
        }
        i=0;
        int k=nums.size()-1;
        while(q){
            i++;
            if(m<=i&&i<=n){
                q->val=nums[k];
                k--;
            }
            q=q->next;
        }
        return head;
    }
};`
