### ISSUE TITLE
画解算法 260-只出现一次的数字 III

### ISSUE THREAD

**Issue by guanpengchn** [guanpengchn/blog#16]

**Comment by dljgs1** [comment]
集合查询法（JS）：
var singleNumber = function(nums) {
    var dog = {};
    nums.forEach((n)=>{dog[n]?delete dog[n]:dog[n]=true;})
    return Object.keys(dog)
};

位运算法（python2）
class Solution(object):
    def singleNumber(self, nums):
        """
        :type nums: List[int]
        :rtype: List[int]
        """
        xor = reduce(lambda x,y:x^y,nums)
        first_bit = [1<<i for i in range(32) if (1<<i)&xor][0]
        res = reduce(lambda x,y:x^y,[n for n in nums if n&first_bit])
        return [res,res^xor]

**Comment by nc0812** [comment]
new
